server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery/eureka/

spring:
  profiles:
    active: kubernetes
  datasource:
    url: ${DATABASE_URI}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_URI}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
