server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true


spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  cloud:
    stream:
      bindings:
        user-channel:
          destination: user-processor
        course-channel:
          destination: course-processor

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zuul:
  sensitive-headers: Cookie
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

